### ISSUE TITLE
Bug - ao criar usuários

### ISSUE THREAD

**Issue by AlexandreFerreiraRJ** [alerj/docigp#102]
![image](https://user-images.githubusercontent.com/4698779/56771043-f03aa100-678b-11e9-89f0-c62289fd9422.png)

**Comment by BMasquio** [comment]
Dá um migrate:fresh. O password é nullable. Isso foi alterado em uma migration antiga(antes de entrar em produção)

![image](https://user-images.githubusercontent.com/15174854/56810615-13f1fb80-680d-11e9-95e0-a4f90219d180.png)
