### ISSUE TITLE
Nem todos os centros de custo estão aparecendo

### ISSUE THREAD

**Issue by BMasquio** [alerj/docigp#104]
![image](https://user-images.githubusercontent.com/15174854/56825534-cd61c880-682f-11e9-8fee-d27dc8110ec6.png)

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito

**Comment by BMasquio** [comment]
Fechar a #92 tb

**Comment by antonioribeiro** [comment]
Tive que refatorar muito isso por outros motivos, então nossas mudanças vão conflitar
