### ISSUE TITLE
Formulário de novo lançamento abrindo em momento errado

### ISSUE THREAD

**Issue by Hugogemino** [alerj/docigp#108]
![image](https://user-images.githubusercontent.com/40171645/56913841-0648aa00-6a89-11e9-92d1-d9362c92933a.png)

ao clicar no botão de nova despesa, caso feche a janela ao invés de cancelar, ao clicar em depositar ou verificar, o formulário de nova despesa abre ao fundo.

e ao fechar o formulário ou clicar fora do formulário de nova despesa, o botão para de funcionar

**Comment by BMasquio** [comment]
Esse formulário de lançamento fica fechando inesperadamente tb (muito recorrente).

**Comment by BMasquio** [comment]
Eu consertei um erro que estava dando nesse modal. Não sei se tem a ver com o do Hugo.

A princípio, está funcionando normalmente.

**Comment by BMasquio** [comment]
Fechando pois já está funcionadno
