### ISSUE TITLE
o Filtro sem mandato, está trazendo pessoas q sairam e voltaram

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/docigp#110]
Removi da legislatura e adicionei novamente, ao filtrar por sem madato, o deputado apareceu

![image](https://user-images.githubusercontent.com/20132028/56919796-e2d92b80-6a97-11e9-9e40-325b731ed8c3.png)

**Comment by AlexandreFerreiraRJ** [comment]
@orlandovinicius1987 já fez.
