### ISSUE TITLE
Atualizar os centros de custo de acordo com o ato 645 (que alterou o 641)

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/docigp#122]

**Comment by BMasquio** [comment]
**II
Novo texto**
serviços e produtos postais previstos nos contratos celebrados pela Assembleia Legislativa, vedadas as aquisições de selos e remessas de cartões postais, até o limite mensal inacumulável de 20% do valor da DOCIGP

**Antigo texto**
serviços e produtos postais previstos nos contratos celebrados pela Assembleia Legislativa, vedadas as aquisições de selos e remessas de cartões postais, até o limite mensal inacumulável de 5% do valor da DOCIGP;


**VIII
Novo texto**
divulgação da sua atividade parlamentar, exceto nos cento e vinte dias anteriores à data das eleições de âmbito federal, estadual ou municipal e obedecidas as demais vedações da legislação eleitoral, através de serviços gráficos, serviços de criação de conteúdo digital, impulsionamento de mídias e monitoramento da atividade parlamentar em redes sociais, até o limite mensal inacumulável de 30% do valor da DOCIGP;

**Antigo texto**
divulgação da sua atividade parlamentar, exceto nos cento e vinte dias anteriores à data das eleições de âmbito federal, estadual ou municipal e obedecidas as demais vedações da legislação eleitoral, através de serviços gráficos ou digitais, até o limite mensal inacumulável de 30% do valor da DOCIGP;

**V**
Revogado

**Comment by BMasquio** [comment]
Alterações no sistema:
II - Alterar o limite de 5% para 20%
VIII - Nada, pois no sistema só consta "Divulgação da sua atividade parlamentar, exceto nos cento e vinte dias anteriores à data das eleições de âmbito federal, estadual ou municipal"
V - Para mim, é bom não mexer pois o ato 645 entrou em vigor em maio, sendo que em abril é possível usar o gasto como alimentação. A ACI vai controlar daí em diante? Colocamos um campo "revoked_at" e validamos a data do lançamento?

@antonioribeiro

**Comment by antonioribeiro** [comment]
II - esses limites não são controlados pelo sistema, são?
V - revoked_at: ok

Tem que alterar o arquivo pdf (linkado no botão), e juntar a alteração nele, pra quando o usuário baixar chegar tudo pra ele.

**Comment by BMasquio** [comment]
II - Eu não usei esse limit para nada até agora. Dei uma olhada no código e tb não parece ter nada usando.

**Comment by antonioribeiro** [comment]
Tem não, deixamos aí pra um futuro que talvez nem aconteça e também essas regras de percentuais são mais complexas, um campo não é suficiente pra definir, mas o Zé Luiz ja falou que prefere que eles mesmos controlem isso, pq vão ter problemas que só serão admnistraveis humanamente

**Comment by BMasquio** [comment]
Validação do centro de custo

![image](https://user-images.githubusercontent.com/15174854/58287522-97a8f480-7d87-11e9-9bc2-92bb9f210202.png)

**Comment by BMasquio** [comment]
Para alterar o II, preciso que as mudanças que fiz estejam em produção, pois havia uma validação que tirei.

![image](https://user-images.githubusercontent.com/15174854/58287742-2a499380-7d88-11e9-9b15-c50283948de2.png)

**Comment by BMasquio** [comment]
Tem algum jeito mais fácil de conseguir esse ato 645 sem ter que editar na mão?

Esse pdf da 641 vc fez como?

**Comment by antonioribeiro** [comment]
Merged

**Comment by antonioribeiro** [comment]
PDF: eu recebi. Mas agora tem que abrir ele no Adobe Acrobat e acrescentar essa página nova, nada demais
