### ISSUE TITLE
Precisa estar logado para mudar o perPage

### ISSUE THREAD

**Issue by BMasquio** [alerj/docigp#141]
![image](https://user-images.githubusercontent.com/15174854/62308460-c1535b80-b45b-11e9-9dea-f945ccada66f.png)

**Comment by antonioribeiro** [comment]
Precisa estar logado pra gravar na tabela de usuários.
Mas se o usuário não estiver logado tem que funcionar, digo, mudar a quantidade visualmente.

**Comment by BMasquio** [comment]
Feito

**Comment by antonioribeiro** [comment]
@BMasquio, 

Independentemente de ser verbose ou não, quando é Artisan Command, a gente sempre deve mostrar algo para o usuário ver o que está se passando:

![image](https://user-images.githubusercontent.com/3182864/63124190-1c6b6f00-bf81-11e9-84e2-d356bcaeac4c.png)

Com isso eu vi também que ele está atualizando tudo, inclusive os registros de transporte que ele vai atualizar, tem que excluir esses caras da query.

Veja se consegue também desligar os eventos durante essa atualização, por favor. Porque se isso for feito no servidor, vai levar horas pra terminar.

**Comment by BMasquio** [comment]
Resolvido
