### ISSUE TITLE
Bug no cadastro do Usuário

### ISSUE THREAD

**Issue by ricardocamargo07** [alerj/docigp#202]
O nome não está como elemento obrigatório.

**Comment by BMasquio** [comment]
@ricardocamargo07 , as regras de validação das requisições ficam guardadas na função `rules()` de uma Request, que é uma classe responsável por tratar a requisição.

Dá uma olhada em como essas validações são feitas:
https://laravel.com/docs/5.8/validation

No nosso caso, as classes relativas aos usuários são:
`app/Http/Requests/UserStore.php`
`app/Http/Requests/UserUpdate.php`

O que deve resolver é colocar o campo 'name' como obrigatório dessa forma:

![image](https://user-images.githubusercontent.com/15174854/72812032-8dedce80-3c3f-11ea-86db-014185f28856.png)

Faz isso aí e vê se resolve. Testa a criação de usuários e a edição de um usuário já criado.

**Comment by BMasquio** [comment]
Feito
