### ISSUE TITLE
Mudanças no Arredondamento

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/docigp#203]
Foi comunicado que a contabilidade vai considerar o arredondamento para baixo nos valores, então é necessário verificar se vai gerar diferença entre os valores recebidos pelos deputados.

**Comment by BMasquio** [comment]
Falta só fazer a migration agora para atualizar os valores atuais de **janeiro e fevereiro** de 2020

**Comment by BMasquio** [comment]
Feito
