### ISSUE TITLE
Editar o comentário

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/docigp#226]
- [x] Aumentar o Tamanho da Tela e o tamanho da letra.
- [x] Mostrar no lançamento a quantidade de comentários.
- [ ] Criar botão no comentário para o tornar visível ao Deputado.

**Comment by BMasquio** [comment]
A quantidade de comentários é uma coluna só para a ACI

**Comment by BMasquio** [comment]
Tem que limitar o espaço possível na tabela para o comentário

![image](https://user-images.githubusercontent.com/15174854/77078395-48e2e000-69d5-11ea-92bd-0179cd13998c.png)

**Comment by BMasquio** [comment]
Tem que mostrar na tabela de cima o número de comentários tb. A coluna só pode ser vista pelo controle interno.

**Comment by BMasquio** [comment]
A quantidade de comentários foi adicionada. Falta só mudar a caixa de texto

**Comment by BMasquio** [comment]
Feito
