### ISSUE TITLE
O Saldo de Transporte não está sendo atualizado direito

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/docigp#228]
Quando é excluído um lançamento após o orçamento fechado, o saldo acumulado passa a ficar errado.

Possível solução, criar botão / função de ajustar saldo.

**Comment by BMasquio** [comment]
Quando cria lançamento também.

Parece que o sistema não está entendendo sempre que o transporte de saldo precisa ser recalculado.

**Comment by BMasquio** [comment]
Feito
