### ISSUE TITLE
Adicionar uma lista de CNPJs bloqueados

### ISSUE THREAD

**Issue by BMasquio** [alerj/docigp#329]
Há uma restrição para uso de empresas com parentes de até terceiro grau dos deputados. Por isso, vamos criar um checkbox nos fornecedores para esses CNPJs bloqueados. A ACI vai fazer esse controle dos CNPJs a serem inseridos.

Se o CNPJ estiver bloqueado, mostrar a seguinte mensagem na visão dos usuários do sistema(não mostrar para os cidadãos):
```
"CPF/CNPJ bloqueado pelo DOCIGP"
```

Exemplo:

![image](https://user-images.githubusercontent.com/15174854/93388862-bc10c600-f841-11ea-9d12-d0bd8e121748.png)

**Comment by BMasquio** [comment]
- [ ] Adicionar uma coluna `is_blocked` na tabela `providers`

- [ ] Adicionar um checkbox no cadastro de favorecidos com 'Bloqueado pelo DOCIGP"

![image](https://user-images.githubusercontent.com/15174854/93617001-d2d32c00-f9ab-11ea-922d-c4a96f8ebf2d.png)

- [ ] Adicionar o comentário em vermelho nos lançamentos dos CNPJs bloqueados

![image](https://user-images.githubusercontent.com/15174854/93617015-d6ff4980-f9ab-11ea-91e9-cfffa6cd19f7.png)

**Comment by BMasquio** [comment]
Feito

**Comment by orlandovinicius1987** [comment]
A ACI na Homologação fez os seguintes comentários:

- Alterar o texto para "Bloqueado **pela** DOCIGP"
- Destacar os cnpjs bloqueados com cores diferentes.

Issue: #345
