### ISSUE TITLE
Adicionar tabela para ocorrências de fornecedores

### ISSUE THREAD

**Issue by BMasquio** [alerj/docigp#397]
- Na view de edição de cada fornecedor, criar uma tabela com as ocorrências em lançamentos desse fornecedor, tendo o deputado que usou, a data, valor etc

- Só a ACI poderá acessar

![image](https://user-images.githubusercontent.com/15174854/102918596-f358c980-4465-11eb-946c-ae71cb90f4c9.png)

**Comment by orlandovinicius1987** [comment]
Feito

**Comment by BMasquio** [comment]
Blz. Pode abrir o Pull Request para submeter
