### ISSUE TITLE
Crud de Providers (Fornecedores / favorecidos)

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/docigp#41]
- [x] CRU(-D)
- [x] Colocar no painel de controle
- [x] Colocar no menu
- [x] Máscara em CPF/CNPJ
- [x] Verificar CPF/CNPJ
- [x] Testar

**Comment by antonioribeiro** [comment]
Não funciona, botão de gravar não faz nada

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito

**Comment by antonioribeiro** [comment]
@BMasquio você fez tudo?
Pelo menos a máscara ficou faltando

**Comment by antonioribeiro** [comment]
Fiz as máscaras.
