### ISSUE TITLE
Criar plano de contas TCE

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/docigp#43]
E fazer um DE-PARA com a tabela de centros de custos.

**Comment by BMasquio** [comment]
Feito.

#352 

Conforme combinamos, colocamos em produção a funcionalidade de gerar relatório anual no sistema DOCIGP. O relatório é gerado em PDF e pode ser gerado a partir da escolha de um deputado e um ano. Além disso, foram definidas as seguintes regras:

 

- A funcionalidade fica restrita aos usuários do Controle Interno

 

- Os lançamentos não publicados não são contabilizados no relatório

 

- Os lançamentos são relacionados aos seus respectivos centros de custo, conforme os nomes a seguir:

    - I e seus descendentes => Passagens

    - II e seus descendentes => Serv. Postais

    - III e seus descendentes => Manut. Gab.

    - IV e seus descendentes => Custeio Gab.

    - V e seus descendentes => Alimentação

    - VI.a => Loc. veículos

    - VI.b => 'Locomoção

    - VII e seus descendentes => Combustíveis

    - VIII e seus descendentes => Divulgação

    - IX e seus descendentes => Cursos

    - X e seus descendentes => Diárias

    - XI e seus descendentes => Tarifas

 

- Os lançamentos com o centro de custo "VI - Outras despesas com locomoção" não devem ser contabilizados

 

- VALOR ANUAL RECEBIDO corresponde à soma de todos os lançamentos relativos a "1 - Crédito em conta-corrente"

 

- VALOR ANUAL DEVOLUÇÕES corresponde à soma de todos os lançamentos relativos a "4 - Devolução de saldo"

 

- VALOR ANUAL DESPESAS corresponde à soma de todos os lançamentos contabilizados na tabela principal

 

- SITUAÇÃO é dada como REGULAR se (VALOR ANUAL RECEBIDO = VALOR ANUAL DEVOLUÇÕES + VALOR ANUAL DESPESAS) e como IRREGULAR caso contrário
