### ISSUE TITLE
Textos explicativos

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/docigp#61]
- [ ] Na visão de "Transparência"
- [ ] Explicações de observação sobre a conta e sobre gastar mais do que a cota mensal
- [ ] Orçamento requerido não utilizado no extrato
- [ ] Saldo orçamentário do mês anterior
- [ ] Nota de rodapé
- [ ] Os valores estão sob análise

**Comment by BMasquio** [comment]
Por enquanto, não estão reclamando e não estou sabendo das mudanças. Fechando a issue. Reabrir em caso de acontecer algo novo.
