### ISSUE TITLE
Impossível incluir um centro de custo

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/docigp#82]
O que é sigla superior?
Os selects estão vazios, era pra ter select ali?

![image](https://user-images.githubusercontent.com/3182864/56177331-9f30ed00-5fd4-11e9-93e9-5d8e7034231c.png)

**Comment by BMasquio** [comment]
Pelo que entendi, o código superior seria um select dos centros de custo já existentes. O código pode ser um texto livre. Seria isso?

Frequência é texto livre tb?

**Comment by antonioribeiro** [comment]
Só não faz sentido.
Essa tabela é um plano de contas, temos o código da conta e o código do pai
(caso esta conta seja um sub-código), o filho (a conta) terá código único,
ele não vai se repetir, eventualmente a gente poderia criar um select para
o pai, mas também acho que não precisa, pelo menos por enquanto porque isso
não vai mudar tão cedo e ainda que entre uma conta nova, dá pra digitar
tranquilamente o código do pai.

Antonio Carlos Ribeiro
acr@antoniocarlosribeiro.com

(+55) 21-9-8088-2233 (celular TIM)
(+55) 21-2556-3164 (fixo residencial)

skype: antoniocarlosribeiro

_______________

*I must say I find television very educational. The minute somebody turns
it on, I go to the library and read a good book.** (*

*Devo dizer que acho televisão muito educativo. Quando alguém a liga, vou à
biblioteca e leio um bom livro.) (Groucho Marx)*

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito
