### ISSUE TITLE
Validar CPF / CNPJ no Request de Providers

### ISSUE THREAD

**Issue by BMasquio** [alerj/docigp#88]

**Comment by BMasquio** [comment]
Fazendo

**Comment by antonioribeiro** [comment]
Você incluiu um pacote novo pra verificar CPF/CNPJ, certo?

Remove ele e cria um Validator pra isso, usando `app/Services/CpfCnpj/CpfCnpj.php`.

Eu criei serviço há um tempo já, porque precisava de outras coisas que aquele validador não vai dar, então se temos um vamos usar ele pra tudo, ok?

**Comment by BMasquio** [comment]
Ok

**Comment by BMasquio** [comment]
Feito
