### ISSUE TITLE
Somatório de documentos/lançamentos não leva em consideração os não publicados

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/docigp#94]

**Comment by BMasquio** [comment]
Não entendi. Parece que está ok.

![image](https://user-images.githubusercontent.com/15174854/56828151-11a49700-6837-11e9-9d05-5868a3ed0875.png)

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Parece que foi resolvido já

![image](https://user-images.githubusercontent.com/15174854/56915675-85d87800-6a8d-11e9-94af-2ee60b19a049.png)

**Comment by antonioribeiro** [comment]
Sim, eu tinha resolvido um, mas parece que tinha alguma outra coisa. Como vc disse que faltava isso ainda, achei que tivesse aparecido nos testes
